# Generated by Django 5.1.4 on 2025-01-11 19:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('insights', models.TextField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(help_text="FontAwesome class (e.g., 'fab fa-python')", max_length=50)),
                ('category', models.CharField(choices=[('LANG', 'Programming Languages'), ('FRAME', 'Frameworks & Libraries'), ('TOOL', 'Development Tools'), ('CLOUD', 'Cloud & Platforms'), ('DB', 'Databases'), ('MOBILE', 'Mobile Development'), ('WEB', 'Web Services & APIs'), ('AI', 'AI & Data Science'), ('SEC', 'Security & Testing'), ('OTHER', 'Other Tech')], default='OTHER', max_length=10)),
            ],
            options={
                'verbose_name': 'Tech Icon',
                'verbose_name_plural': 'Tech Icons',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField(default=0, help_text='Proficiency level (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('icon', models.ForeignKey(blank=True, help_text='Select an icon for this skill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='portfolio_app.techicon')),
            ],
            options={
                'ordering': ['-proficiency'],
            },
        ),
    ]
